@startuml
|Користувач|
start
:Відкрити текстовий редактор;
:Обрати текст для редагування;

|Web Interface|
:Завантажити поточну версію;
fork
  |History Manager|
  :Отримати історію змін;
  :Підготувати дані версій;
fork again
  |Text Editor|
  :Ініціалізувати редактор;
  :Відобразити інструменти редагування;
end fork

|Web Interface|
:Показати текст та історію;

|Користувач|
while (Редагування активне?) is (так)
  :Внести зміни в текст;
  
  |Text Editor|
  :Перевірити правопис;
  :Підсвітити зміни;
  
  |Text Formatter|
  :Застосувати форматування;
  :Оновити пунктуацію;
  
  |Web Interface|
  :Оновити відображення;
  
  |Користувач|
  if (Зберегти зміни?) then (так)
    :Підтвердити збереження;
    
    |Text Formatter|
    :Фіналізувати форматування;
    
    |Corpus Generator|
    :Оновити розмітку;
    :Зберегти в БД;
    
    |History Manager|
    :Створити нову версію;
    :Оновити історію змін;
    
    |Web Interface|
    :Оновити інтерфейс;
    
    |Користувач|
  else (ні)
    :Продовжити редагування;
  endif
endwhile (ні)

:Завершити редагування;
stop

@enduml 